# Generated by Django 5.0 on 2023-12-26 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodingQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_text', models.TextField()),
                ('input_text', models.CharField(max_length=2000)),
                ('output_text', models.CharField(max_length=2000)),
                ('input_example', models.CharField(max_length=1024)),
                ('output_example', models.CharField(max_length=1024)),
                ('topic', models.CharField(max_length=100)),
                ('problem_hardness', models.IntegerField(choices=[(0, 'easy'), (1, 'medium'), (2, 'hard')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ProblemStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coding.codingquestions')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TestCases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_case_input', models.TextField()),
                ('test_case_output', models.TextField()),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coding.codingquestions')),
            ],
        ),
    ]
