# Generated by Django 5.0 on 2024-01-06 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemstatus',
            name='solution',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
