# Generated by Django 5.0 on 2024-01-11 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0002_problemstatus_solution'),
    ]

    operations = [
        migrations.AddField(
            model_name='codingquestions',
            name='xp',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
