# Generated by Django 5.0 on 2024-02-01 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0003_codingquestions_xp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codingquestions',
            name='primary_text',
            field=models.TextField(unique=True),
        ),
    ]
