# Generated by Django 5.0 on 2024-02-10 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0004_alter_codingquestions_primary_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='codingquestions',
            name='title',
            field=models.TextField(default='hi', unique=True),
            preserve_default=False,
        ),
    ]
