# Generated by Django 5.0 on 2024-02-10 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0005_codingquestions_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codingquestions',
            name='title',
            field=models.TextField(),
        ),
    ]
