# Generated by Django 5.0 on 2024-02-20 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0008_codingquestions_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemstatus',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coding.codingquestions', unique=True),
        ),
    ]
