# Generated by Django 5.0 on 2024-01-10 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='MaxLevel',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
    ]
