# Generated by Django 5.0 on 2024-02-11 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_tournament_maxlevel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='StartDate',
            field=models.DateField(),
        ),
    ]
