# Generated by Django 5.0 on 2024-02-20 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0004_alter_tournament_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='Photo',
            field=models.CharField(max_length=256),
        ),
    ]
