# Generated by Django 5.0 on 2024-01-10 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.CharField(default=None, max_length=24, null=True),
            preserve_default=False,
        ),
    ]
