# Generated by Django 5.0 on 2024-02-01 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermatching',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
