# Generated by Django 5.0 on 2024-02-18 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0005_usermatching_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermatching',
            name='question',
        ),
    ]
