# Generated by Django 5.0 on 2024-02-18 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0008_remove_usermatching_question'),
        ('coding', '0008_codingquestions_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermatching',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='coding.codingquestions'),
            preserve_default=False,
        ),
    ]
